### ISSUE TITLE
USB scope not found

### ISSUE THREAD

**Issue by marcosjl** [tinwhisker/Owon-VDS1022#2]
Hi,
I'm trying to use the Java app for owon vds 1022 on Yosemite OS.
So far the only way I've found to manage USB interaction is by using this 2 additional steps to your doc:
1/ install libusb librairies (command brew install libusb, to get 1.0.0 libs in /usr/local/lib)
2/ downloading from the Net libusb-0.1.4.dylib for macos and installing it under /usr/local/lib

When the app is trying to link to the USB scope (status goes to "Linking") , I get those messages before status gets back to Offline:

ch.ntb.usb.USBException: LibusbJava.usb_set_configuration: Operation timed out
	at com.owon.uppersoft.vds.core.usb.CDevice.claim_interface(CDevice.java:609)
	at com.owon.uppersoft.vds.core.usb.CDevice.simulateOpen(CDevice.java:868)
	at com.owon.uppersoft.vds.core.usb.CDevice.simulateOpen(CDevice.java:828)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager._getUSBSource(USBSourceManager.java:129)
	at com.owon.uppersoft.vds.source.comm.PortFilterTiny.collectPorts(PortFilterTiny.java:46)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager.refreshUSBPort(USBSourceManager.java:110)
	at com.owon.uppersoft.dso.source.comm.detect.USBLoopChecker.checkUSBDevice(USBLoopChecker.java:93)
	at com.owon.uppersoft.dso.source.comm.USBDaemonHelper.onNotConnecting(USBDaemonHelper.java:31)
	at com.owon.uppersoft.vds.machine.InfiniteDaemonTiny0.onNotConnecting(InfiniteDaemonTiny0.java:30)
	at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:74)
	at com.owon.uppersoft.dso.global.ControlAppsTiny$1.run(ControlAppsTiny.java:37)

Any hint really appreciated !

Regards
José L. Marcos

**Comment by tinwhisker** [comment]
Updated the repo - I think this might fix similar problems.
