### ISSUE TITLE
Can't get this Work with ubuntu!

### ISSUE THREAD

**Issue by Pluscrafter** [tinwhisker/Owon-VDS1022#7]
I had follow your manual and the scope won't get recognized. In the lsusb the scope is shown as a OWON PDS6062T.

**Comment by reddn** [comment]
Im pretty close to getting it to work.  I installed libusb-dev:386  32bit java (dont think it matters, but you never know).    Then it gets mad that it can't find libusbpp-0.1.so.4  i symlinked it to libusb-0.1.so.4 and now it gives me a 
'''
:~/Downloads/wineOWON/plugins$ sudo java -jar org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar
ch.ntb.usb.USBException: LibusbJava.usb_set_configuration: could not set config 1: Connection timed out
	at com.owon.uppersoft.vds.core.usb.CDevice.claim_interface(CDevice.java:609)
	at com.owon.uppersoft.vds.core.usb.CDevice.simulateOpen(CDevice.java:868)
	at com.owon.uppersoft.vds.core.usb.CDevice.simulateOpen(CDevice.java:828)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager._getUSBSource(USBSourceManager.java:129)
	at com.owon.uppersoft.vds.source.comm.PortFilterTiny.collectPorts(PortFilterTiny.java:46)
	at com.owon.uppersoft.dso.source.usb.USBSourceManager.refreshUSBPort(USBSourceManager.java:110)
	at com.owon.uppersoft.dso.source.comm.detect.USBLoopChecker.checkUSBDevice(USBLoopChecker.java:93)
	at com.owon.uppersoft.dso.source.comm.USBDaemonHelper.onNotConnecting(USBDaemonHelper.java:31)
	at com.owon.uppersoft.vds.machine.InfiniteDaemonTiny0.onNotConnecting(InfiniteDaemonTiny0.java:30)
	at com.owon.uppersoft.dso.source.comm.Flow.run(Flow.java:74)
	at com.owon.uppersoft.dso.global.ControlAppsTiny$1.run(ControlAppsTiny.java:37)
'''

There is a github repo of libusbpp. so ill actually try to compile that to make it work

**Comment by reddn** [comment]
^^^ machine is a linux mint 19 (18.04 i think)

**Comment by florentbr** [comment]
See https://github.com/tinwhisker/Owon-VDS1022/issues/6#issuecomment-478625152
